behaviors:
  HallwayAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 10000
      learning_rate: 0.0003
      learning_rate_schedule: linear
      beta: 0.0075
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 2
    max_steps: 15000000
    time_horizon: 25
    summary_freq: 10000
    keep_checkpoints: 50
    checkpoint_interval: 500000
    threaded: true
    network_settings:
      vis_encoder_type: simple
      normalize: true
      hidden_units: 64
      num_layers: 2
#      memory:
#        sequence_length: 8
#        memory_size: 8
    reward_signals:
      extrinsic:
        strength: 1
        gamma: 0.95
      gail:
        gamma: 0.95
        strength: 1
        network_settings:
          normalize: true
          hidden_units: 64
          num_layers: 2
          vis_encode_type: simple
        learning_rate: 0.00025
        use_actions: false
        use_vail: false
        demo_path: config\circles.demo
    behavioral_cloning:
      demo_path: config\circles.demo
      steps: 1000000
      strength: 1
      samples_per_update: 0
      batch_size: 128
      num_epoch: 3
env_settings:
  env_path: ..\Builds\HallwayVoluntaryFullyObservabele\UnityEnvironment
  base_port: 5005
  num_envs: 3
  seed: -1
engine_settings:
  time_scale: 30
checkpoint_settings:
  run_id: hallwayVoluntaryCircles3
  #initialize_from: hallwayVoluntaryFullyObs2
  #load_model: false
  #resume: true
  #force: false
  #train_model: false
  #inference: false
debug: false
torch_settings:
  device: cuda
environment_parameters:
  #decision_period: 2
  environments_per_unity_process: 3
  multi_scene: 0
