name: ml-agents-remastered
dependencies:
- python=3.8
- pip
- pip:
  - -e ml-agents-envs
  - -e ml-agents

  - torch==1.11.0+cu113
  - torchvision==0.12.0+cu113
  - torchaudio==0.11.0
  - --extra-index-url https://download.pytorch.org/whl/cu113

  - matplotlib
  - jupyterlab